### ISSUE TITLE
As a writer...

### ISSUE THREAD

**Issue by dtysky** [dsh0416/cocos-gal#2]
This is what i did about 1 years ago...

https://github.com/dtysky/Gal2Renpy

Hope for helping you... as a reference.

One idea is:

This DSL is just for logic, we can support different engines by parser, like web application...

**Comment by dsh0416** [comment]
What this project is going to do is more likely to be what `renpy` did. But as this lib runs as a framework, you could still add any super OpenGL magic to it to expand your project with anything you want. The lib would be a part of your project and does not need any pre-compiled matter.

**Comment by dtysky** [comment]
Thanks for your reply, I understand and look forward to it.  
Hope my DSL format could help you, as a gal writer,  I think it is not bad.
